---
apiVersion: apiregistration.k8s.io/v1beta1
kind: APIService
metadata:
  name: v1beta1.custom.metrics.k8s.io
spec:
  group: custom.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  service:
    name: prometheus-adapter
    namespace: monitoring
  groupPriorityMinimum: 100
  versionPriority: 100
---
